repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
# disabled (for now?) because it messes with docstring placement -- this breaks instance
#   variable documentation on classes
#  - repo: https://github.com/bwhmather/ssort
#    rev: v0.11.6
#    hooks:
#      - id: ssort
