name: push actions
on: [push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.9', '3.8']
        poetry-version: [1.2.2]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry install
        run: poetry install
      - name: mypy
        # exclude examples in CI because some 3.10 features are used
        run: poetry run mypy . --exclude examples
      - name: run tests
        run: poetry run pytest
      - name: run all examples
        if: matrix.python-version == 3.10
        run: poetry run bash run_all_examples.sh
      - name: linting
        run: poetry run flake8 --exclude examples,codegen,bench --ignore E741,W503,F405,F403,F401
