name: push actions
on: [push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']
        poetry-version: [1.1.13]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: poetry install
        run: poetry install
      - name: mypy
        run: poetry run mypy .
      - name: run tests
        run: poetry run pytest
      - name: linting
        run: poetry run flake8
